# MACHINE LEARNING

In [32]:
import pandas as pd

In [34]:
pd.read_csv('imdb_top_movies_1980_2026.csv')

,imdb_id,title,original_title,year,runtime_minutes,genres,average_rating,num_votes,imdb_url
0,tt0111161,The Shawshank Redemption,The Shawshank Redemption,1994,142.0,Drama,9.3,3182733,https://www.imdb.com/title/tt0111161
1,tt0468569,The Dark Knight,The Dark Knight,2008,152.0,"Action,Crime,Drama",9.1,3161984,https://www.imdb.com/title/tt0468569
2,tt1375666,Inception,Inception,2010,148.0,"Action,Adventure,Sci-Fi",8.8,2811692,https://www.imdb.com/title/tt1375666
3,tt0137523,Fight Club,Fight Club,1999,139.0,"Crime,Drama,Thriller",8.8,2601984,https://www.imdb.com/title/tt0137523
4,tt0816692,Interstellar,Interstellar,2014,169.0,"Adventure,Drama,Sci-Fi",8.7,2521607,https://www.imdb.com/title/tt0816692
...,...,...,...,...,...,...,...,...,...
16247,tt3544218,Belgica,Belgica,2016,127.0,Drama,6.7,5001,https://www.imdb.com/title/tt3544218
16248,tt0101733,Dil Hai Ki Manta Nahin,Dil Hai Ki Manta Nahin,1991,154.0,"Adventure,Comedy,Drama",7.2,5001,https://www.imdb.com/title/tt0101733
16249,tt10994688,The Binge,The Binge,2020,98.0,Comedy,5.3,5000,https://www.imdb.com/title/tt10994688
16250,tt0263743,Billionaire,Milyarder,1987,96.0,"Comedy,Drama",7.5,5000,https://www.imdb.com/title/tt0263743
16251,tt1921078,Saint Petersburg,San Peterzburg,2010,120.0,"Comedy,Crime,Drama",6.4,5000,https://www.imdb.com/title/tt1921078

In [35]:
pd.read_csv('imdb_top_movies_1980_2026.csv' ,header=1)

,tt0111161,The Shawshank Redemption,The Shawshank Redemption.1,1994,142,Drama,9.3,3182733,https://www.imdb.com/title/tt0111161
0,tt0468569,The Dark Knight,The Dark Knight,2008,152.0,"Action,Crime,Drama",9.1,3161984,https://www.imdb.com/title/tt0468569
1,tt1375666,Inception,Inception,2010,148.0,"Action,Adventure,Sci-Fi",8.8,2811692,https://www.imdb.com/title/tt1375666
2,tt0137523,Fight Club,Fight Club,1999,139.0,"Crime,Drama,Thriller",8.8,2601984,https://www.imdb.com/title/tt0137523
3,tt0816692,Interstellar,Interstellar,2014,169.0,"Adventure,Drama,Sci-Fi",8.7,2521607,https://www.imdb.com/title/tt0816692
4,tt0109830,Forrest Gump,Forrest Gump,1994,142.0,"Drama,Romance",8.8,2492584,https://www.imdb.com/title/tt0109830
...,...,...,...,...,...,...,...,...,...
16246,tt3544218,Belgica,Belgica,2016,127.0,Drama,6.7,5001,https://www.imdb.com/title/tt3544218
16247,tt0101733,Dil Hai Ki Manta Nahin,Dil Hai Ki Manta Nahin,1991,154.0,"Adventure,Comedy,Drama",7.2,5001,https://www.imdb.com/title/tt0101733
16248,tt10994688,The Binge,The Binge,2020,98.0,Comedy,5.3,5000,https://www.imdb.com/title/tt10994688
16249,tt0263743,Billionaire,Milyarder,1987,96.0,"Comedy,Drama",7.5,5000,https://www.imdb.com/title/tt0263743
16250,tt1921078,Saint Petersburg,San Peterzburg,2010,120.0,"Comedy,Crime,Drama",6.4,5000,https://www.imdb.com/title/tt1921078

In [37]:
pd.read_csv('imdb_top_movies_1980_2026.csv' ,index_col='imdb_id')

,title,original_title,year,runtime_minutes,genres,average_rating,num_votes,imdb_url
imdb_id,,,,,,,,
tt0111161,The Shawshank Redemption,The Shawshank Redemption,1994,142.0,Drama,9.3,3182733,https://www.imdb.com/title/tt0111161
tt0468569,The Dark Knight,The Dark Knight,2008,152.0,"Action,Crime,Drama",9.1,3161984,https://www.imdb.com/title/tt0468569
tt1375666,Inception,Inception,2010,148.0,"Action,Adventure,Sci-Fi",8.8,2811692,https://www.imdb.com/title/tt1375666
tt0137523,Fight Club,Fight Club,1999,139.0,"Crime,Drama,Thriller",8.8,2601984,https://www.imdb.com/title/tt0137523
tt0816692,Interstellar,Interstellar,2014,169.0,"Adventure,Drama,Sci-Fi",8.7,2521607,https://www.imdb.com/title/tt0816692
...,...,...,...,...,...,...,...,...
tt3544218,Belgica,Belgica,2016,127.0,Drama,6.7,5001,https://www.imdb.com/title/tt3544218
tt0101733,Dil Hai Ki Manta Nahin,Dil Hai Ki Manta Nahin,1991,154.0,"Adventure,Comedy,Drama",7.2,5001,https://www.imdb.com/title/tt0101733
tt10994688,The Binge,The Binge,2020,98.0,Comedy,5.3,5000,https://www.imdb.com/title/tt10994688
tt0263743,Billionaire,Milyarder,1987,96.0,"Comedy,Drama",7.5,5000,https://www.imdb.com/title/tt0263743
tt1921078,Saint Petersburg,San Peterzburg,2010,120.0,"Comedy,Crime,Drama",6.4,5000,https://www.imdb.com/title/tt1921078

In [33]:
pd.read_csv('imdb_top_movies_1980_2026.csv' ,usecols=['title','genres','average_rating'])

                          title                   genres  average_rating
0      The Shawshank Redemption                    Drama             9.3
1               The Dark Knight       Action,Crime,Drama             9.1
2                     Inception  Action,Adventure,Sci-Fi             8.8
3                    Fight Club     Crime,Drama,Thriller             8.8
4                  Interstellar   Adventure,Drama,Sci-Fi             8.7
...                         ...                      ...             ...
16247                   Belgica                    Drama             6.7
16248    Dil Hai Ki Manta Nahin   Adventure,Comedy,Drama             7.2
16249                 The Binge                   Comedy             5.3
16250               Billionaire             Comedy,Drama             7.5
16251          Saint Petersburg       Comedy,Crime,Drama             6.4

[16252 rows x 3 columns]

In [42]:
pd.read_csv('imdb_top_movies_1980_2026.csv' ,skiprows=[1,3,4,5,6,7])

,imdb_id,title,original_title,year,runtime_minutes,genres,average_rating,num_votes,imdb_url
0,tt0468569,The Dark Knight,The Dark Knight,2008,152.0,"Action,Crime,Drama",9.1,3161984,https://www.imdb.com/title/tt0468569
1,tt0133093,The Matrix,The Matrix,1999,136.0,"Action,Sci-Fi",8.7,2243917,https://www.imdb.com/title/tt0133093
2,tt0120737,The Lord of the Rings: The Fellowship of the Ring,The Lord of the Rings: The Fellowship of the Ring,2001,178.0,"Adventure,Drama,Fantasy",8.9,2203274,https://www.imdb.com/title/tt0120737
3,tt0167260,The Lord of the Rings: The Return of the King,The Lord of the Rings: The Return of the King,2003,201.0,"Adventure,Drama,Fantasy",9.0,2161551,https://www.imdb.com/title/tt0167260
4,tt0114369,Seven,Se7en,1995,127.0,"Crime,Drama,Mystery",8.6,2017173,https://www.imdb.com/title/tt0114369
...,...,...,...,...,...,...,...,...,...
16241,tt3544218,Belgica,Belgica,2016,127.0,Drama,6.7,5001,https://www.imdb.com/title/tt3544218
16242,tt0101733,Dil Hai Ki Manta Nahin,Dil Hai Ki Manta Nahin,1991,154.0,"Adventure,Comedy,Drama",7.2,5001,https://www.imdb.com/title/tt0101733
16243,tt10994688,The Binge,The Binge,2020,98.0,Comedy,5.3,5000,https://www.imdb.com/title/tt10994688
16244,tt0263743,Billionaire,Milyarder,1987,96.0,"Comedy,Drama",7.5,5000,https://www.imdb.com/title/tt0263743
16245,tt1921078,Saint Petersburg,San Peterzburg,2010,120.0,"Comedy,Crime,Drama",6.4,5000,https://www.imdb.com/title/tt1921078

In [41]:
pd.read_csv('imdb_top_movies_1980_2026.csv' ,nrows=10)

,imdb_id,title,original_title,year,runtime_minutes,genres,average_rating,num_votes,imdb_url
0,tt0111161,The Shawshank Redemption,The Shawshank Redemption,1994,142,Drama,9.3,3182733,https://www.imdb.com/title/tt0111161
1,tt0468569,The Dark Knight,The Dark Knight,2008,152,"Action,Crime,Drama",9.1,3161984,https://www.imdb.com/title/tt0468569
2,tt1375666,Inception,Inception,2010,148,"Action,Adventure,Sci-Fi",8.8,2811692,https://www.imdb.com/title/tt1375666
3,tt0137523,Fight Club,Fight Club,1999,139,"Crime,Drama,Thriller",8.8,2601984,https://www.imdb.com/title/tt0137523
4,tt0816692,Interstellar,Interstellar,2014,169,"Adventure,Drama,Sci-Fi",8.7,2521607,https://www.imdb.com/title/tt0816692
5,tt0109830,Forrest Gump,Forrest Gump,1994,142,"Drama,Romance",8.8,2492584,https://www.imdb.com/title/tt0109830
6,tt0110912,Pulp Fiction,Pulp Fiction,1994,154,"Crime,Drama",8.8,2431723,https://www.imdb.com/title/tt0110912
7,tt0133093,The Matrix,The Matrix,1999,136,"Action,Sci-Fi",8.7,2243917,https://www.imdb.com/title/tt0133093
8,tt0120737,The Lord of the Rings: The Fellowship of the Ring,The Lord of the Rings: The Fellowship of the Ring,2001,178,"Adventure,Drama,Fantasy",8.9,2203274,https://www.imdb.com/title/tt0120737
9,tt0167260,The Lord of the Rings: The Return of the King,The Lord of the Rings: The Return of the King,2003,201,"Adventure,Drama,Fantasy",9.0,2161551,https://www.imdb.com/title/tt0167260

In [43]:
pd.read_csv('imdb_top_movies_1980_2026.csv' ,encoding='latin-1')

,imdb_id,title,original_title,year,runtime_minutes,genres,average_rating,num_votes,imdb_url
0,tt0111161,The Shawshank Redemption,The Shawshank Redemption,1994,142.0,Drama,9.3,3182733,https://www.imdb.com/title/tt0111161
1,tt0468569,The Dark Knight,The Dark Knight,2008,152.0,"Action,Crime,Drama",9.1,3161984,https://www.imdb.com/title/tt0468569
2,tt1375666,Inception,Inception,2010,148.0,"Action,Adventure,Sci-Fi",8.8,2811692,https://www.imdb.com/title/tt1375666
3,tt0137523,Fight Club,Fight Club,1999,139.0,"Crime,Drama,Thriller",8.8,2601984,https://www.imdb.com/title/tt0137523
4,tt0816692,Interstellar,Interstellar,2014,169.0,"Adventure,Drama,Sci-Fi",8.7,2521607,https://www.imdb.com/title/tt0816692
...,...,...,...,...,...,...,...,...,...
16247,tt3544218,Belgica,Belgica,2016,127.0,Drama,6.7,5001,https://www.imdb.com/title/tt3544218
16248,tt0101733,Dil Hai Ki Manta Nahin,Dil Hai Ki Manta Nahin,1991,154.0,"Adventure,Comedy,Drama",7.2,5001,https://www.imdb.com/title/tt0101733
16249,tt10994688,The Binge,The Binge,2020,98.0,Comedy,5.3,5000,https://www.imdb.com/title/tt10994688
16250,tt0263743,Billionaire,Milyarder,1987,96.0,"Comedy,Drama",7.5,5000,https://www.imdb.com/title/tt0263743
16251,tt1921078,Saint Petersburg,San Peterzburg,2010,120.0,"Comedy,Crime,Drama",6.4,5000,https://www.imdb.com/title/tt1921078

In [49]:
pd.read_csv('imdb_top_movies_1980_2026.csv' ,encoding='latin-1', ,on_bad_lines=False)

,imdb_id,title,original_title,year,runtime_minutes,genres,average_rating,num_votes,imdb_url
0,tt0111161,The Shawshank Redemption,The Shawshank Redemption,1994,142.0,Drama,9.3,3182733,https://www.imdb.com/title/tt0111161
1,tt0468569,The Dark Knight,The Dark Knight,2008,152.0,"Action,Crime,Drama",9.1,3161984,https://www.imdb.com/title/tt0468569
2,tt1375666,Inception,Inception,2010,148.0,"Action,Adventure,Sci-Fi",8.8,2811692,https://www.imdb.com/title/tt1375666
3,tt0137523,Fight Club,Fight Club,1999,139.0,"Crime,Drama,Thriller",8.8,2601984,https://www.imdb.com/title/tt0137523
4,tt0816692,Interstellar,Interstellar,2014,169.0,"Adventure,Drama,Sci-Fi",8.7,2521607,https://www.imdb.com/title/tt0816692
...,...,...,...,...,...,...,...,...,...
16247,tt3544218,Belgica,Belgica,2016,127.0,Drama,6.7,5001,https://www.imdb.com/title/tt3544218
16248,tt0101733,Dil Hai Ki Manta Nahin,Dil Hai Ki Manta Nahin,1991,154.0,"Adventure,Comedy,Drama",7.2,5001,https://www.imdb.com/title/tt0101733
16249,tt10994688,The Binge,The Binge,2020,98.0,Comedy,5.3,5000,https://www.imdb.com/title/tt10994688
16250,tt0263743,Billionaire,Milyarder,1987,96.0,"Comedy,Drama",7.5,5000,https://www.imdb.com/title/tt0263743
16251,tt1921078,Saint Petersburg,San Peterzburg,2010,120.0,"Comedy,Crime,Drama",6.4,5000,https://www.imdb.com/title/tt1921078

In [50]:
pd.read_csv('imdb_top_movies_1980_2026.csv').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16252 entries, 0 to 16251
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   imdb_id          16252 non-null  object
 1   title            16252 non-null  object
 2   original_title   16252 non-null  object
 3   year             16252 non-null  int64
 4   runtime_minutes  16251 non-null  float64
 5   genres           16246 non-null  object
 6   average_rating   16252 non-null  float64
 7   num_votes        16252 non-null  int64
 8   imdb_url         16252 non-null  object
dtypes: float64(2), int64(2), object(5)
memory usage: 1.1+ MB

In [58]:
pd.read_csv('imdb_top_movies_1980_2026.csv',dtype{'runtime_minutes':int})

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1299641402.py, line 1)

In [71]:
dfs=pd.read_csv('imdb_top_movies_1980_2026.csv' ,chunksize=5000)

In [72]:
for chunks in dfs:
    print(chunks.shape)

(5000, 9)
(5000, 9)
(5000, 9)
(1252, 9)

In [74]:
1.# working with json

1.0

In [75]:
pd.read_json('test.json')

         id                                        ingredients
0     18009  [baking powder, eggs, all-purpose flour, raisi...
1     28583  [sugar, egg yolks, corn starch, cream of tarta...
2     41580  [sausage links, fennel bulb, fronds, olive oil...
3     29752  [meat cuts, file powder, smoked sausage, okra,...
4     35687  [ground black pepper, salt, sausage casings, l...
...     ...                                                ...
9939  30246  [large egg yolks, fresh lemon juice, sugar, bo...
9940  36028  [hot sauce, butter, sweet potatoes, adobo sauc...
9941  22339  [black pepper, salt, parmigiano reggiano chees...
9942  42525  [cheddar cheese, cayenne, paprika, plum tomato...
9943   1443  [cold water, olive oil, lime wedges, garlic cl...

[9944 rows x 2 columns]